# Generated by Django 6.1.1 on 2026-09-17 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewellery_type', models.CharField(help_text='e.g. Ring, Necklace, Bangle', max_length=100)),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], default='gold', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Requested weight in grams', max_digits=8)),
                ('description', models.TextField(help_text='Design description / requirements')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='customization_refs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed - Price Estimated'), ('approved', 'Approved by Customer'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('goldsmith_making_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('goldsmith_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
