# Generated by Django 6.1.1 on 2026-09-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('stone', 'Precious Stone'), ('other', 'Other Raw Material')], default='gold', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='grams', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'ordering': ['type', 'material_name'],
            },
        ),
    ]
